dependencies:
  - python=3.7
  - jupyterlab=3.1.9
  - pip
  - numpy=1.20.3
  - pandas=1.3.2
  - matplotlib=3.4.2
  - seaborn=0.11.1
  - scikit-learn=0.23.2
  - scipy=1.7.1
  - joblib=1.0.1
  - tqdm=4.62.2
  - matplotlib-venn=0.11.6
  - pysam=0.16.0.1
  - pip:
    - venn=0.1.3
    - upsetplot=0.6.0
